name: patmorais
favicon: null
layout_spectrum: 0.9693877
typography_spectrum: 0.8684211
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1F1F30'
    - '#5C5C66'
    - '#B59A9A'
    - '#91B4E9'
    - '#F3914C'
  brandStrength: 0.5794844
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
